### ISSUE TITLE
(DrawDeathScreen) Экран смерти игрока

### ISSUE THREAD

**Issue by vasthecat** [csit-sgu/mit-game-151#14]
Данная функция выполняется когда игрок умер от прикосновения к противнику. В целом, реализовать эту функцию можно практически как угодно, но минимально допустимый вариант - текст, сообщающий о смерти игрока на фоне чёрного прямоугольника.

**Comment by fanta512** [comment]
Здравствуйте. Вы можете открыть эту задачу?

**Comment by fanta512** [comment]
мне нужно ее выбрать чтобы в разделе Assignees было мое имя. я сделать этого не могу
